version: '2'

services:
    ne-api:
        image: ne-api:latest
        build:
            context: ../
            dockerfile: Netease API/Dockerfile
            
        ports:
            - "2003:2003"
        networks:
            - nginx_default
        container_name: "ne-api"
networks:
    nginx_default:
        external: true
