version: '2'

services: 
    ne-api:
        image: ne-api:latest
        build: ./
        ports: 
            - "2003:2003"
        networks: 
            - mynet
        container_name: "ne-api"
networks: 
    mynet:
        external: true