version: "2"

services:
    mukai-playlist:
        image: mukai-playlist:latest
        build: ./
        ports:
            - "2010:2010"
        networks:
            mynet:
                ipv4_address: 172.18.0.11
        container_name: "mukai-playlist"
networks:
    mynet:
        external: true
