version: '2'

services: 
    mukai-gateway:
        image: mukai-gateway:latest
        build: ./
        ports: 
            - "9999:9999"
        networks: 
            mynet:
                 ipv4_address: 172.18.0.10
        container_name: "mukai-gateway"
networks: 
    mynet:
        external: true