version: '3'

services:
  mukai-ng:
    image: mukai-ng:latest
    build:
      context: ../
      dockerfile: Angular/Dockerfile
    ports:
      - "8900:80"
    networks:
      - nginx_default
    container_name: "mukai-ng"
networks:
  nginx_default:
    external: true
