version: '2'

services:
    kuwo-api:
        image: kuwo-api:latest
        build:
            context: ../
            dockerfile: Kuwo API/Dockerfile
        ports:
            - "2002:2002"
        networks:
            - nginx_default
        container_name: "kuwo-api"
networks:
    nginx_default:
        external: true
