version: '2'

services: 
    migu-api:
        image: "migu-api:latest"
        build: ./
        
        ports: 
            - "3500:3500"
        networks: 
            mynet:
                 ipv4_address: 172.18.0.8

networks: 
    mynet:
        external: true